server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix:classpath: /templates2/
    suffix: .htmdl
  application:
    images: C:\Users\gjacquet\Pictures
    dependances: D:\carrousel\pack-carrousel\src\main\resources\ihm\static
    templates: D:\carrousel\pack-carrousel\src\main\resources\ihm\templates