server:
  port: 8082

spring:
  thymeleaf:
    cache: false
    enabled: true
  application:
    images: /root/carrousel/images
    dependances: /root/carrousel/ihm/static
    templates: /root/carrousel/ihm/static