server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    enabled: true
  application:
    images: C:\Users\gjacquet\Pictures\carrousel
    dependances: D:\carrousel\pack-carrousel\src\main\resources\ihm\static
    templates: D:\carrousel\pack-carrousel\src\main\resources\ihm\templates