server:
  port: 8082

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix:file: /templates/
    suffix: .html
  application:
    cheminImages: /root/carrousel/images
    dependancesIhm: /root/carrousel/dependancesIhm